// ============================================================================
// PLUMIA — corrections-config.js  v8.00
// COLOR_MAP, CONFIG, GROUPS, CORRECTIONS — namespace window.PLUMIA
// Expuesto como window.PLUMIA.* para compatibilidad con Office Add-in
// ============================================================================
(function() {
window.PLUMIA = {};
window.PLUMIA.CONFIG_VERSION = '9.31';
console.log('📦 corrections-config.js v9.31 cargado');
window.PLUMIA.COLOR_MAP = {
  1:{name:"Rojo",hex:"FF0000",type:"text"},
  2:{name:"Amarillo",hex:"FFD966",type:"highlight"},
  3:{name:"Verde claro",hex:"92D050",type:"highlight"},
  4:{name:"Naranja",hex:"FF9900",type:"highlight"},
  5:{name:"Turquesa",hex:"00B0F0",type:"highlight"},
  6:{name:"Rosa",hex:"FF69B4",type:"bracket"},
  7:{name:"Azul",hex:"0070C0",type:"text"},
  8:{name:"Lavanda",hex:"C9B8FF",type:"highlight"},
  9:{name:"Violeta",hex:"7030A0",type:"highlight"},
};

window.PLUMIA.CONFIG = {
  model:"claude-sonnet-4-6",
  maxTokens:8192,
  wordsPerToken:0.75,
  inputPricePerToken:0.000003,
  outputPricePerToken:0.000015,
  chunkSizeWords:3000,
  chunkOverlapWords:200,
  coherenceChunkSizeWords:80000,
  revisionSuffix:"REVISION",
  statsSuffix:"ESTADISTICAS",
};

window.PLUMIA.GROUPS = [
  {id:"pronouns",  label:"Pronombres y deixis"},
  {id:"lexicon",   label:"Léxico y vocabulario"},
  {id:"style",     label:"Estilo y fluidez"},
  {id:"grammar",   label:"Gramática"},
  {id:"orthotypo", label:"Ortotipografía"},
  {id:"coherence", label:"Coherencia narrativa", requiresFullDoc:true},
];

window.PLUMIA.CORRECTIONS = [
  {id:"leismo", groupId:"pronouns", label:"Leísmos, laísmos y loísmos", description:"Uso incorrecto de le, la, lo como complemento", colorId:1, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en gramática española. Analiza el texto en busca de leísmos, laísmos y loísmos REALES.

DEFINICIONES ESTRICTAS:
- LAÍSMO: usar "la/las" como COMPLEMENTO INDIRECTO (CI). Ej: "La dije que viniera" → "Le dije". PRUEBA: ¿puedes añadir "a ella" sin que suene redundante y el verbo no admite "¿qué?" sino "¿a quién le?"? Entonces es CI y "la" sería laísmo.
- LOÍSMO: usar "lo/los" como COMPLEMENTO INDIRECTO (CI). Ej: "Lo di el libro" → "Le di". PRUEBA: igual que el laísmo.
- LEÍSMO: usar "le/les" como COMPLEMENTO DIRECTO (CD) para inanimados o femeninos. Ej: "Le vi" (cosa) → "Lo vi". El leísmo de persona masculina singular ("le vi" = "lo vi") está aceptado por la RAE; no lo marques.

CLAVE PARA NO EQUIVOCARTE — test CD vs CI:
- Si el verbo responde a "¿qué?" o "¿a quién?" (directo) → el pronombre correcto es lo/la/los/las (CD). Usar "la" o "lo" aquí ES CORRECTO, NO es laísmo ni loísmo.
- Si el verbo responde a "¿a quién le?" o "¿para quién?" (indirecto) → el pronombre correcto es le/les (CI). Usar "la" o "lo" aquí SÍ sería laísmo o loísmo.

VERBOS QUE RIGEN CD (usar "lo/la" es CORRECTO, nunca marcar como error):
reconocer, ver, oír, conocer, querer, amar, abrazar, besar, coger, tomar, llevar, notar, encontrar, buscar, llamar (convocar), echar de menos, ayudar, escuchar, mirar, observar, sentir, imaginar, recordar, olvidar.

NO marques como error:
- "la reconociera" (reconocer = CD ✓)
- "la cogiese" (coger = CD ✓)
- "lo abrazó" (abrazar = CD ✓)
- "lo echaba de menos" (echar de menos = CD ✓)
- "lo notó cansado" (notar = CD ✓)
- "lo llamó" cuando significa convocar/llamar a alguien (CD ✓)

Texto a analizar:\n{TEXT}\n\nREGLA ABSOLUTA: Si un fragmento no contiene error real, NO lo incluyas en findings. Nunca añadas un finding con explanation "correcto", "descartado" o "no aplica".\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"type":"leismo|laismo|loismo","originalText":"fragmento exacto del texto","correction":"forma correcta","explanation":"explicación breve indicando qué función tiene el pronombre"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ningún error real: {"findings":[]}`},

  {id:"ambiguedad_pronominal", groupId:"pronouns", label:"Ambigüedades pronominales", description:"Pronombres con referente poco claro", colorId:8, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de ambigüedades pronominales: casos en que pronombres como él, ella, lo, la, le, se, su, su no tienen un referente inequívoco porque hay dos o más personajes del mismo género a los que podría referirse.\n\nPATRONES QUE DEBES DETECTAR SIEMPRE:\n- Dos «él» o «ella» consecutivos o próximos que claramente se refieren a personas distintas (ej: «Él no dijo nada. Tampoco él.»)\n- «él/ella» tras una escena con varios personajes del mismo género sin que quede claro a cuál se refiere\n- Verbos en tercera persona (entró, miró, dijo, se levantó…) cuyo sujeto es ambiguo porque hay varios candidatos\n- «su» o «se» cuando el poseedor/reflexivo podría ser cualquiera de dos o más personajes mencionados\n- Cambio de referente pronominal sin marcador explícito (el pronombre pasa de un personaje a otro sin indicarlo)\n\nNO señales:\n- Pronombres cuyo referente es inequívoco por contexto inmediato\n- Errores de leísmo, laísmo o loísmo\n- Casos donde solo hay un personaje del género correspondiente en el párrafo\n- «se» reflexivo cuando la estructura sintáctica determina inequívocamente el sujeto: p. ej. «al ver cómo X hacía algo, se desbordó» — quien ve es quien se desborda, no hay ambigüedad real aunque haya dos personajes en la frase\n- Verbos reflexivos en consecuencias de cláusulas causales o temporales donde el actor de la cláusula principal es el mismo que realiza la acción («al ver… se emocionó», «cuando lo oyó, se echó a llorar»)\n- «su/sus» cuando uno de los posibles referentes está ausente físicamente de la escena (recordado, pensado, mencionado como ausente): si un personaje piensa en otro que no está presente, «sus lágrimas caían a sus pies» solo puede referirse al personaje presente\n- Pronombres anafóricos que retoman un verbo explícito e inmediato en la misma oración: «han tardado en hacerlo» donde «hacerlo» retoma claramente el verbo de la cláusula anterior — esto no es ambigüedad, es anáfora verbal normal\n- Verbos en plural cuyo único sujeto posible son los dos únicos personajes activos en la escena: «apagaron las luces» tras «se abrazó a él» no es ambiguo — si solo hay dos personas activas, el plural solo puede referirse a ambas\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto del texto","pronoun":"pronombre o verbo ambiguo","possibleReferents":["personaje1","personaje2"],"explanation":"por qué es ambiguo","suggestion":"posible reformulación"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"repeticion_lexica", groupId:"lexicon", label:"Repeticiones léxicas cercanas", description:"Misma palabra repetida en corta distancia", colorId:2, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de repeticiones léxicas cercanas: la misma palabra (o su raíz) repetida en un radio de 3-5 líneas, sin intención estilística. No señales artículos, preposiciones, conjunciones, ni repeticiones deliberadas. Tampoco señales nombres propios (nombres de personajes, lugares o entidades): esas repeticiones se analizan por separado.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"word":"palabra base","occurrences":["fragmento 1","fragmento 2"],"explanation":"breve explicación","synonyms":["sin1","sin2","sin3"]}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"verbos_comedin", groupId:"lexicon", label:"Verbos comodín", description:"Abuso de hacer, poner, tener, dar, haber…", colorId:4, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de verbos comodín usados en exceso: hacer, poner, tener, dar, haber, decir, ver, ir, venir, coger, cuando podría usarse un verbo más preciso. Solo señala casos donde empobrezca claramente el estilo.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","verb":"verbo comodín","explanation":"por qué es mejorable","alternatives":["alt1","alt2","alt3"]}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"sustantivos_genericos", groupId:"lexicon", label:"Sustantivos genéricos", description:"Abuso de cosa, tema, aspecto, situación…", colorId:4, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de sustantivos genéricos: cosa, tema, aspecto, situación, elemento, cuestión, problema, algo, asunto, hecho, usados donde podría emplearse un término más concreto.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","genericWord":"palabra genérica","explanation":"por qué es mejorable","alternatives":["alt1","alt2","alt3"]}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"muletillas", groupId:"lexicon", label:"Muletillas narrativas", description:"Expresiones repetidas que no aportan valor", colorId:4, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de muletillas: palabras o expresiones que aparecen con demasiada frecuencia y no aportan información nueva. Ej: "en cierto modo", "de alguna manera", "de repente" repetido, "entonces", "básicamente", "realmente". Solo señala las que aparezcan al menos 2 veces o sean claramente innecesarias.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"expression":"muletilla","occurrences":["fragmento 1","fragmento 2"],"explanation":"por qué es muletilla","alternatives":["alt1","alt2","eliminar"]}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"pleonasmos", groupId:"lexicon", label:"Pleonasmos", description:"Palabras innecesarias que repiten información", colorId:4, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de pleonasmos REALES: palabras cuyo significado ya está COMPLETAMENTE contenido en otra palabra de la misma expresión, de modo que su eliminación no cambia el significado.\n\nEjemplos de pleonasmos REALES:\n- "subir arriba" (subir ya implica dirección hacia arriba)\n- "bajar abajo", "entrar dentro", "salir fuera"\n- "ver con mis propios ojos" (ver implica que usas tus ojos)\n- "volver a reincidir" (reincidir ya implica repetición)\n- "pausar momentáneamente" si pausa ya implica lo momentáneo\n\nNO son pleonasmos (no los marques):\n- Expresiones lexicalizadas normales: "volver a casa", "ir al trabajo", "llegar tarde"\n- Énfasis o intensificación estilística: "muy por encima", "completamente solo", "justo en ese momento" — el énfasis es una figura retórica válida, no un error\n- Errores gramaticales o de concordancia: "tres de segundos" es un error sintáctico, no un pleonasmo\n- Cualquier expresión donde la segunda palabra añade localización, tiempo u otro matiz no contenido en la primera\n- Verbos que requieren un complemento para especificar el tipo o causa: "desbordarse de felicidad/miedo/rabia", "rebosar de energía", "estallar de alegría/ira" — el complemento es necesario porque sin él el verbo queda incompleto o indefinido\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto del texto","explanation":"qué palabra repite exactamente el significado de cuál otra","correction":"forma sin redundancia"}]}\nDevuelve MÁXIMO 10 hallazgos. Si no encuentras ningún pleonasmo real: {"findings":[]}`},

  {id:"adverbios_mente", groupId:"style", label:"Adverbios en -mente", description:"Evalúa cada adverbio en -mente: adecuado o mejorable para la narrativa", colorId:3, includesSynonyms:true, directFix:false,
   prompt:`Eres un editor literario experto en español. Analiza el texto buscando adverbios terminados en \"-mente\".\n\nREGLA FUNDAMENTAL: el campo \"adverb\" debe ser la palabra EXACTA del texto que termina literalmente en \"-mente\" (ej: \"rápidamente\", \"claramente\"). NUNCA pongas la raíz sin \"-mente\" (no \"rápida\", no \"clara\"), ni palabras relacionadas que no terminen en \"-mente\" (no \"improviso\", no \"absorbente\"). Si la palabra no termina en \"-mente\" en el texto, NO la incluyas.\n\nPara CADA adverbio en \"-mente\" que encuentres:\n1. Cita la frase original exacta del texto.\n2. Indica el adverbio detectado (debe terminar en \"-mente\").\n3. Evalúa su uso:\n   a) \"Adecuado\": aporta matiz, ritmo o precisión difícil de sustituir.\n   b) \"Mejorable\": redundante, débil o sustituible por algo más expresivo.\n4. Si es \"Mejorable\", propone 2 alternativas que:\n   - NO usen adverbios en \"-mente\" ni otros adverbios.\n   - Prioricen verbos más precisos, acciones concretas o recursos narrativos.\n   - Suenen naturales dentro de una novela.\n\nIMPORTANTE: No elimines adverbios que funcionen bien. Respeta los que aporten valor literario. Si el texto no contiene ninguna palabra terminada en \"-mente\", devuelve findings:[].\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{\"findings\":[{\"originalText\":\"frase exacta del texto\",\"adverb\":\"adverbio exacto terminado en -mente\",\"evaluation\":\"Adecuado|Mejorable\",\"explanation\":\"por qué es adecuado o mejorable\",\"alternatives\":[\"alternativa 1\",\"alternativa 2\"]}]}\nSi no hay adverbios en -mente: {\"findings\":[]}`},

  {id:"voz_pasiva", groupId:"style", label:"Voz pasiva innecesaria", description:"Construcciones pasivas que podrían ser activas", colorId:5, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de construcciones en VOZ PASIVA REAL que resultarían más naturales en voz activa.

SOLO señala construcciones que cumplan UNA de estas dos formas:
1. Pasiva perifrástica: auxiliar SER/ESTAR conjugado + participio + (opcionalmente "por" + agente). Ejemplos válidos: "fue abierto por", "es conocido por", "había sido destruido".
2. Pasiva refleja donde "se" actúa como marca de pasividad con sujeto paciente explícito. Ejemplo válido: "se publicaron los resultados".

NO señales (son falsos positivos habituales):
- Participios adjetivales que modifican un sustantivo dentro de una frase nominal, aunque vayan seguidos de "por": "proyecto lanzado por X", "experimentos llevados a cabo", "ángel sacado de una iglesia", "telescopio regalado". Prueba: si puedes sustituir el participio por un adjetivo cualquiera sin cambiar la estructura, NO es pasiva.
- Construcciones activas con sujeto implícito o indeterminado: "le habían regalado", "le dijeron que", "le avisaron de".
- Oraciones de relativo con participio: "los que fueron enviados" solo si el contexto hace natural la forma pasiva.
- Construcciones con "se" que son pronominales o medias, no pasivas: "se llamaba", "se fue", "se levantó".

No señales cuando la forma pasiva sea la más natural en contexto o no haya agente claro que recuperar.

Texto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"frase completa con la construcción pasiva","explanation":"estructura pasiva exacta encontrada y por qué revisarla","activeVersion":"reformulación en voz activa"}]}\nDevuelve MÁXIMO 10 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"frases_largas", groupId:"style", label:"Frases demasiado largas", description:"Oraciones de +40 palabras que dificultan la lectura", colorId:6, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de frases excesivamente largas que dificulten la comprensión o rompan el ritmo.

CRITERIO OBLIGATORIO: la frase debe tener MÁS DE 40 PALABRAS. No señales frases más cortas aunque te parezcan complejas — la complejidad sin longitud excesiva no es motivo para marcarlas. Cuenta las palabras antes de señalar.

Texto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"frase completa exacta","wordCount":45,"explanation":"por qué dificulta la lectura","suggestion":"cómo dividirla o simplificarla"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"nombres_propios", groupId:"style", label:"Exceso de nombres propios", description:"Repetición excesiva de nombres propios cercanos", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de nombres propios que se repiten con demasiada frecuencia en un fragmento corto, cuando podrían sustituirse por pronombres u otras referencias.\nREGLA CRÍTICA: Solo señala un nombre propio si aparece LITERALMENTE 2 o más veces dentro del mismo fragmento analizado. Si el nombre aparece una única vez en el texto, NO lo señales bajo ningún concepto, aunque creas que podría repetirse en otra parte del documento.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"name":"nombre propio","occurrences":["fragmento 1","fragmento 2"],"explanation":"por qué resulta excesivo","suggestion":"cómo aligerarlo"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"ritmo_narrativo", groupId:"style", label:"Ritmo narrativo", description:"Desequilibrios de ritmo entre escena y longitud de frases", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un editor literario experto en español. Analiza el texto en busca de desequilibrios de ritmo ESTRUCTURAL. Céntrate SOLO en:\n1) Acumulación de frases muy cortas y telegráficas en escenas descriptivas, de atmósfera o de calma, donde ese ritmo entrecortado rompe el tono contemplativo.\n2) Párrafos con densidad muy desigual sin intención estilística (un párrafo de 2-3 palabras junto a otro de 150+ palabras en el mismo tono emocional).\n\nNO señales NUNCA:\n- Frases largas: eso lo analiza la categoría «Frases demasiado largas» — no dupliques ese análisis aquí bajo ningún concepto\n- Textos de menos de 100 palabras\n- Frases cortas en escenas de acción o tensión (son estilísticamente correctas)\n- Frases cortas que sean deliberadamente impactantes o poéticas\n\nSolo señala casos donde el desequilibrio sea CLARO, EVIDENTE y PERJUDICIAL para la lectura.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","sceneType":"descripción|atmósfera|reflexión","issue":"descripción del desequilibrio","suggestion":"cómo mejorar el ritmo"}]}\nSi no encuentras ninguno o el texto es demasiado corto: {"findings":[]}`},

  {id:"numeros_letras", groupId:"style", label:"Números en letra", description:"Números del 0-99 que en texto literario deben escribirse con letras", colorId:3, includesSynonyms:false, directFix:false, prompt:''},

  {id:"gerundios", groupId:"grammar", label:"Gerundios incorrectos", description:"Gerundio de posterioridad y otros usos incorrectos", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector gramatical experto en español. Analiza el texto en busca de gerundios incorrectos: 1) Gerundio de posterioridad: acción posterior a la principal. Ej: "Salió de casa, encontrando a Juan". 2) Gerundio especificativo: "Una ley regulando el tráfico" → "que regula". 3) Gerundio como adjetivo: "Una caja conteniendo libros".\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","gerund":"gerundio problemático","errorType":"posterioridad|especificativo|adjetivo","explanation":"por qué es incorrecto","correction":"reformulación correcta"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"interrogativas_tilde", groupId:"grammar", label:"Tildes en interrogativos y exclamativos", description:"qué/que, cómo/como, cuándo/cuando, quién/quien, dónde/donde, cuánto/cuanto, cuál/cual", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de errores en el uso de tildes diacríticas en palabras interrogativas y exclamativas.\n\nREGLAS:\n- CON tilde (interrogativo/exclamativo): qué, cómo, cuándo, quién/quiénes, dónde, cuánto/cuánta/cuántos/cuántas, cuál/cuáles\n  → Preguntas directas: «¿Qué quieres?», «¿Cómo estás?», «¿Cuándo llegas?»\n  → Preguntas indirectas: «No sé qué pensar», «Me preguntó cómo lo hice», «Ignoro cuándo volverá»\n  → Interrogativas paralelas con «ni»: «Nadie sabía qué pensar ni cómo actuar», «No quedaba claro cuándo ocurrió ni quién lo decidió ni dónde estaba» — el «ni» no convierte el interrogativo en comparativo\n  → «cómo» + infinitivo: «no sabía cómo actuar», «sin saber cómo resolverlo», «ignoraba cómo hacerlo» — siempre interrogativa indirecta, NUNCA comparativo\n  → «cuándo» tras verbos de conocimiento o claridad (saber, entender, quedar claro, ignorar, preguntar…): «quedaba claro cuándo había ocurrido», «no sabía cuándo volvería» — es interrogativa indirecta aunque no haya «¿»\n  → Exclamaciones: «¡Qué bonito!», «¡Cuánto tiempo!», «¡Cómo llueve!»\n- SIN tilde (conjunción/relativo/comparativo): que, como, cuando, quien/quienes, donde, cuanto/cuanta/cuantos/cuantas, cual/cuales\n  → Conjunción: «Dijo que vendría», «Cuando llegué estaba»\n  → «cuando» temporal al inicio de oración (sin verbo de conocimiento previo): «Cuando por fin llegaron», «Cuando acabó todo», «Cuando llegaron al acuerdo» — conjunción temporal, NUNCA lleva tilde. REGLA CRÍTICA: si «cuando» abre la oración principal y no depende de un verbo de duda/conocimiento anterior, es conjunción temporal → sin tilde\n  → Relativo: «El libro que leí», «Fue él quien lo hizo», «La ciudad donde nació»\n  → Comparativo/modal («como» introduce una comparación o modo, no una pregunta): «rápido como el viento», «Como llovía, me quedé», «Tanto como quieras» — CLAVE: si tras «como» hay un infinitivo en contexto de ignorancia o duda, es interrogativa indirecta (cómo), no comparativo\n\nNO señales los casos inmediatamente tras ¿ o ¡ — ya los detecta el motor local. Céntrate en preguntas indirectas y tildes sobrantes en contexto relativo o conjuncional.\n\nREGLA ABSOLUTA: NUNCA incluyas un finding donde «wordForm» y «correctForm» sean la misma palabra (con o sin tilde). Si la palabra ya está escrita correctamente, no la incluyas. Solo reporta errores reales donde la forma detectada difiere de la forma correcta.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto con contexto suficiente","wordForm":"palabra detectada","correctForm":"forma correcta","errorType":"falta_tilde|tilde_sobrante","context":"interrogativo_directo|interrogativo_indirecto|exclamativo|relativo|conjuncion|comparativo","explanation":"por qué es incorrecto"}]}\nSi no encuentras ninguno: {"findings":[]}`},

  {id:"tu_tilde", groupId:"grammar", label:"Uso de «tú» con tilde diacrítica", description:"«tú» (pronombre personal sujeto) vs «tu» (posesivo, ante sustantivo)", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de errores en el uso de «tú» (con tilde diacrítica) y «tu» (sin tilde).\n\nREGLAS:\n- «tú» CON tilde: pronombre personal sujeto («Tú sabes», «Lo hiciste tú», «Eres tú», «¿Lo haces tú?»)\n- «tu» SIN tilde: posesivo determinante, siempre ante sustantivo («tu casa», «tu amor», «tu idea»)\n\nNO señales los casos de «que tu» seguido de puntuación — ya los detecta el motor local.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto con contexto suficiente","tuForm":"tu|tú","correctForm":"tú|tu","function":"pronombre_personal|posesivo","explanation":"por qué es incorrecto"}]}\nSi no encuentras ninguno: {"findings":[]}`},

  {id:"mi_tilde", groupId:"grammar", label:"Uso de «mí» con tilde diacrítica", description:"«mí» (pronombre personal, siempre tras preposición) vs «mi» (posesivo, ante sustantivo)", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de errores en el uso de «mí» (con tilde diacrítica) y «mi» (sin tilde).\n\nREGLAS:\n- «mí» CON tilde: pronombre personal, siempre tras preposición («a mí», «para mí», «de mí», «por mí», «sin mí», «sobre mí», «hacia mí»)\n- «mi» SIN tilde: posesivo, siempre ante sustantivo («mi casa», «mi amor», «mi idea»)\n\nNO señales los casos donde «mi» va seguido de puntuación (coma, punto, etc.) porque ya los detecta el motor local.\nSeñala SOLO los casos claramente incorrectos que requieran análisis de contexto:\n- «mi» tras preposición cuando actúa como pronombre y NO le sigue puntuación inmediata\n- «mí» ante un sustantivo donde claramente actúa como posesivo\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto del texto con contexto suficiente","miForm":"mi|mí","correctForm":"mí|mi","function":"pronombre_personal|posesivo","explanation":"por qué es incorrecto"}]}\nSi no encuentras ninguno: {"findings":[]}`},

  {id:"aun_tilde", groupId:"grammar", label:"Uso de «aún» con tilde diacrítica", description:"«aún» (= todavía) vs «aun» (= incluso/aunque) — detección local de patrones seguros", colorId:7, includesSynonyms:false, directFix:false, prompt:''},

  {id:"si_tilde", groupId:"grammar", label:"Uso de «sí» con tilde diacrítica", description:"«sí» (adverbio/pronombre reflexivo) vs «si» (conjunción condicional)", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de errores en el uso de «sí» (con tilde diacrítica) y «si» (sin tilde).\n\nREGLAS:\n- «sí» CON tilde: adverbio de afirmación ("Sí, quiero"), pronombre personal reflexivo ("volvió en sí", "para sí mismo", "en sí"), sustantivo de aprobación ("dio el sí")\n- «si» SIN tilde: conjunción condicional ("si llueve, me quedo"), interrogativa indirecta ("preguntó si vendría")\n\nSeñala SOLO los casos claramente incorrectos. Presta especial atención a pronombres reflexivos escritos sin tilde: «guardó todo para si» → debe ser «para sí», «volvió en si» → «en sí», «por si mismo» → «por sí mismo», «estaba fuera de si» → «fuera de sí». NO señales casos ambiguos ni la conjunción condicional «si» que ya es correcta.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto del texto con contexto suficiente","siForm":"si|sí","correctForm":"sí|si","function":"adverbio_afirmacion|pronombre_reflexivo|sustantivo|condicional|interrogativa_indirecta","explanation":"por qué es incorrecto"}]}\nSi no encuentras ninguno: {"findings":[]}`},

  {id:"dequeismo", groupId:"grammar", label:"Dequeísmo y queísmo", description:"Uso incorrecto de 'de que' / omisión incorrecta", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector gramatical experto en español. Analiza el texto en busca de: 1) Dequeísmo: "de que" donde solo corresponde "que". Ej: "Pienso de que..." → "Pienso que...". 2) Queísmo: omitir "de" donde es necesaria ante una cláusula "que". Ej: "Estoy seguro que vendrá" → "Estoy seguro de que vendrá".\nREGLA ABSOLUTA: Si al analizar un fragmento concluyes que NO hay error, NO lo incluyas en findings bajo ningún concepto — ni con explanation "correcto", "descartado", "no aplica" ni similar. El array findings solo contiene errores reales confirmados.\nNO señales:\n- Frases sin ninguna cláusula subordinada con "que": si no hay "que" en la frase, no puede haber queísmo ni dequeísmo.\n- Expresiones adverbiales fijas donde "seguro que" no admite "de": "seguro que sí", "seguro que viene", "seguro que tienen" — estas son construcciones correctas e invariables.\n- Complementos nominales sin subordinada: "¿Estás segura de eso?" es correcto (complemento nominal, no cláusula).\n- Frases aparentemente incompletas o abruptas: "No lo veo" puede ser una frase válida e independiente.\n- Errores de leísmo, laísmo o loísmo (eso lo analiza otra categoría)\n- Usos correctos de "de que" después de verbos que lo requieren\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","errorType":"dequeismo|queismo","explanation":"explicación breve","correction":"forma correcta"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"concordancia", groupId:"grammar", label:"Concordancia de género y número", description:"Errores de concordancia sujeto-verbo o sustantivo-adjetivo", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector gramatical experto en español. Analiza el texto en busca de errores de concordancia: 1) Sujeto-verbo: el verbo no concuerda en NÚMERO o PERSONA gramatical con el sujeto (ej: «Los niños corre» → sujeto plural, verbo singular). 2) Sustantivo-adjetivo: el adjetivo no concuerda en género o número. Ignora sujetos compuestos o colectivos con concordancia flexible.\nNO señales NUNCA:\n- Errores de leísmo, laísmo o loísmo (eso lo analiza otra categoría). Por ejemplo, «La dije» es un laísmo, NO un error de concordancia.\n- Referencias posteriores a miembros individuales de un grupo nombrado en plural genérico masculino: en español el plural masculino es genérico e incluye ambos géneros. Ej: «dos hermanos» engloba hermanos y hermanas; decir luego «la hermana mayor» es perfectamente correcto, no es error de concordancia. Lo mismo con «hijos», «amigos», «primos», «compañeros», etc.\n- Inconsistencias de tiempo verbal: que un verbo esté en pretérito indefinido junto a otro en imperfecto (ej: «entró» con «miraba») NO es un error de concordancia — eso lo analiza «Inconsistencia de tiempos verbales». La concordancia sujeto-verbo es SOLO sobre número y persona gramatical, nunca sobre tiempos verbales.\n- Errores de otro tipo que no sean estrictamente de concordancia de número o persona\n- Cualquier frase que simplemente te parezca incorrecta por otros motivos\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","errorType":"sujeto-verbo|sustantivo-adjetivo","explanation":"descripción del error","correction":"forma correcta"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"palabras_sobrantes", groupId:"grammar", label:"Palabras sobrantes o duplicadas", description:"Preposiciones duplicadas, nexos repetidos y partículas intrusivas por escritura espontánea", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de palabras sobrantes o duplicadas: palabras que aparecen de más por inercia de escritura espontánea.\n\nPATRONES QUE DEBES DETECTAR:\n1. Preposiciones duplicadas: "de de", "a a", "en en", "para para", "por por"\n   Ej: "Antes de de irse" → "Antes de irse", "Volvió a a intentarlo" → "Volvió a intentarlo"\n2. Nexos duplicados: "que que", "lo que que", "si si"\n   Ej: "Pensó que que no era posible" → "Pensó que no era posible"\n3. "de" intrusivo entre número y sustantivo: "tres de segundos" → "tres segundos"\n4. Preposiciones mal encadenadas: "depende de en qué" → "depende de qué", "caminó para hacia" → "caminó hacia"\n5. Redundancias de movimiento: "subió arriba hacia arriba", "entró dentro de en la casa"\n\nEn el campo "surplus" pon SOLO la palabra o palabras sobrantes (ej: el segundo "de", el segundo "que").\nEn "originalText" pon el fragmento EXACTO del texto que contiene el error (máx. 60 chars).\n\nNO señales:\n- Pleonasmos estilísticos (esos los detecta otra categoría)\n- Errores de concordancia o conjugación\n- Texto que simplemente te parezca raro sin una palabra duplicada o sobrante clara\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto con el error","surplus":"solo las palabras sobrantes","errorType":"preposicion_duplicada|nexo_duplicado|de_intrusivo|prep_encadenada|movimiento_redundante","explanation":"descripción breve","correction":"fragmento corregido"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"tiempos_verbales", groupId:"grammar", label:"Inconsistencia de tiempos verbales", description:"Mezcla no intencional de indefinido e imperfecto", colorId:5, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector literario experto en español. Analiza el texto en busca de posibles inconsistencias en tiempos verbales del pasado: mezclas no intencionales de pretérito indefinido (canté) e imperfecto (cantaba) dentro de una misma escena. Solo señala los que parezcan descuidos, no los cambios intencionales.\nNO señales:\n- Errores de leísmo, laísmo o loísmo (eso lo analiza otra categoría)\n- Frases con otros tipos de errores gramaticales que no sean de tiempo verbal\n- Cambios de tiempo verbal que son correctos y habituales (descripción en imperfecto + acción en indefinido)\nSolo marca si hay un cambio de tiempo verbal que rompa la coherencia temporal de la escena.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","verbsFound":["verbo indefinido","verbo imperfecto"],"explanation":"por qué podría ser descuido","suggestion":"cómo resolverlo"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"ortotipografia_pura", groupId:"orthotypo", label:"Ortotipografía pura", description:"Guiones, comillas, puntos suspensivos, mayúsculas, signos ¿¡, espaciado", colorId:null, includesSynonyms:false, directFix:true,
   prompt:`Eres un corrector ortotipográfico experto en español. Analiza el texto ÚNICAMENTE en busca de errores tipográficos y ortotipográficos. Corrige:\n1. Guiones de diálogo: guion corto (-) en lugar de raya (—)\n2. Comillas inglesas ("") en lugar de españolas («»)\n3. Tres puntos separados (...) en lugar del carácter tipográfico (…)\n4. Signos de apertura omitidos (¿ ¡)\n5. Espacio ANTES de coma, punto, punto y coma, dos puntos (NO después)\n6. Falta de mayúscula al inicio de párrafo o tras punto final\nNO corrijas NUNCA:\n- Errores gramaticales como leísmos, laísmos o loísmos. Por ejemplo, "La dije" es un laísmo gramatical, NO un error ortotipográfico. NO lo corrijas aquí.\n- Errores de concordancia, dequeísmo, gerundios ni ningún otro error gramatical\n- Estilo, vocabulario o estructura de las frases\nSolo señala y corrige errores puramente tipográficos.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"errorType":"guion|comillas|puntos_suspensivos|signo_apertura|espaciado|mayusculas","originalText":"fragmento exacto","correction":"fragmento corregido","isFirstOccurrence":true,"explanation":"solo si isFirstOccurrence: explicación breve"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"puntuacion_prosa", groupId:"orthotypo", label:"Puntuación en prosa", description:"Comas, puntos y comas, puntos mal puestos o ausentes en prosa narrativa", colorId:6, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector ortotipográfico experto en español. Analiza el texto en busca de errores de puntuación en prosa narrativa (NO en diálogos — esos los analiza otra categoría). Detecta SOLO errores claros e inequívocos:\n1. Coma entre sujeto y verbo: "Ana, fue al mercado" → "Ana fue al mercado" (la coma separa incorrectamente sujeto y verbo).\n2. Coma antes de subordinada adjetiva especificativa: "Los alumnos, que estudian, aprueban" → "Los alumnos que estudian aprueban" (la subordinada es especificativa, no explicativa).\n3. Ausencia de coma en inciso o aposición: "Carlos el director llegó tarde" → "Carlos, el director, llegó tarde".\n4. Ausencia de coma tras conector discursivo al inicio de frase: "Sin embargo no vino" → "Sin embargo, no vino". Conectores: sin embargo, no obstante, por tanto, en cambio, además, por ejemplo, es decir, en efecto, así pues, por consiguiente.\n5. Coma antes de conjunción copulativa en serie binaria: "Llegó, y saludó" → "Llegó y saludó" (no se pone coma antes de «y» en enumeraciones de dos elementos).\n6. Punto y coma donde debe ir punto o coma, si el error es claro.\nREGLA ABSOLUTA: Si un fragmento no contiene error real, NO lo incluyas en findings. Nunca añadas un finding con explanation "correcto", "descartado" o "no aplica".\nNO señales: estilos de puntuación que son elecciones del autor, variantes aceptadas por la RAE, comas expresivas con intención literaria, ni puntuación correcta aunque poco común. NUNCA señales la coma antes de «lo que» cuando introduce una cláusula explicativa o consecutiva que amplía el significado de lo anterior («es infinito, lo que significa que…», «llegó tarde, lo que sorprendió a todos»): esa coma es obligatoria, no un error.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto del texto","errorType":"coma_sujeto_verbo|coma_especificativa|ausencia_coma_inciso|ausencia_coma_conector|coma_innecesaria_y|punto_coma","correction":"fragmento corregido","explanation":"explicación breve de la regla"}]}\nDevuelve MÁXIMO 10 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"puntuacion_dialogo", groupId:"orthotypo", label:"Problemas de puntuación en diálogo", description:"Errores de puntuación en intervenciones y acotaciones", colorId:6, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector ortotipográfico experto en español. Analiza el texto en busca de errores EXCLUSIVAMENTE de puntuación en diálogos. IMPORTANTE: NO detectes ni reportes leísmos, laísmos, loísmos, ambigüedades pronominales ni ningún otro error gramatical — esos pertenecen a otras categorías. Céntrate SOLO en: 1) Falta de raya antes de la acotación: —Hola. dijo → —Hola —dijo. 2) Punto incorrecto antes de acotación. 3) Coma innecesaria antes de raya de cierre. 4) Mayúscula incorrecta en verbo de acotación. 5) Punto tras interrogación/exclamación EXPLÍCITA (con los signos ¿ ? ¡ !): —¿Vienes?. → —¿Vienes? REGLA DURA: si la frase NO contiene ¿ ? ¡ !, NO es un caso de punto tras exclamación/interrogación, aunque el tono sea exclamativo o interrogativo. Vocales alargadas, mayúsculas o énfasis tipográfico NO equivalen a signos de exclamación. 6) Falta de punto tras acotación cuando el diálogo continúa. 7) Coma innecesaria después de interrogación. EXCLUYE cualquier frase que NO sea una intervención directa marcada con raya (—).\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","errorType":"descripción breve del error","correction":"fragmento corregido","explanation":"explicación breve de la regla"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"coherencia_personajes", groupId:"coherence", label:"Coherencia de personajes", description:"Contradicciones en experiencias, habilidades o rasgos físicos", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto narrativo en busca de contradicciones en la caracterización de personajes: 1) Experiencias que se contradicen (afirma que es la primera vez pero ya lo hizo antes). 2) Habilidades que aparecen y desaparecen sin explicación. 3) Rasgos físicos que cambian sin justificación. 4) Conocimiento que un personaje no debería tener.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"characterName":"nombre del personaje","contradictionType":"experiencia|habilidad|rasgo_fisico|conocimiento","occurrence1":{"text":"fragmento exacto","location":"ubicación"},"occurrence2":{"text":"fragmento contradictorio","location":"ubicación"},"explanation":"descripción de la contradicción"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"coherencia_temporal", groupId:"coherence", label:"Coherencia temporal", description:"Inconsistencias en la línea de tiempo del relato", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de inconsistencias temporales: 1) Referencias temporales contradictorias. 2) Edades que no encajan con fechas mencionadas. 3) Estaciones del año contradictorias en el mismo período. 4) Eventos en orden imposible.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"inconsistencyType":"referencia_temporal|edad|estacion|orden_eventos","occurrence1":{"text":"fragmento exacto","location":"ubicación"},"occurrence2":{"text":"fragmento contradictorio","location":"ubicación"},"explanation":"descripción de la inconsistencia"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"coherencia_objetos", groupId:"coherence", label:"Coherencia de objetos y espacios", description:"Objetos que desaparecen o espacios que cambian sin explicación", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de inconsistencias en objetos o espacios: 1) Objeto importante que desaparece sin explicación. 2) Personaje usa un objeto que no podía tener. 3) Distribución de espacios que cambia entre escenas. 4) Personaje lleva algo que olvidó, perdió o entregó antes.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"itemOrSpace":"nombre del objeto/espacio","inconsistencyType":"objeto_desaparece|objeto_imposible|espacio_cambia","occurrence1":{"text":"fragmento exacto","location":"ubicación"},"occurrence2":{"text":"fragmento contradictorio","location":"ubicación"},"explanation":"descripción"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"coherencia_conocimiento", groupId:"coherence", label:"Coherencia de conocimiento", description:"Personajes que saben cosas que no deberían saber aún", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de inconsistencias en el conocimiento de personajes: 1) Un personaje sabe algo que aún no le han contado. 2) Un personaje actúa como si no supiera algo que vivió. 3) El narrador revela información que el personaje focal no podría conocer.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"characterName":"personaje","knowledgeIssue":"descripción","occurrence1":{"text":"fragmento","location":"ubicación"},"occurrence2":{"text":"fragmento contradictorio","location":"ubicación"},"explanation":"descripción"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"tono_voz", groupId:"coherence", label:"Tono y voz narrativa", description:"Cambios bruscos de registro o ruptura del punto de vista", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de inconsistencias CLARAS en tono y voz narrativa: 1) Cambios bruscos e injustificados de registro (de formal a muy coloquial). 2) El narrador rompe explícitamente el punto de vista establecido. 3) Cambios de persona narrativa no justificados. 4) Intrusiones del autor que rompen la ficción.\nNO señales:\n- Textos breves (menos de 200 palabras) donde es imposible evaluar el tono con fiabilidad\n- Errores gramaticales como leísmos que no tienen que ver con el tono\n- Variaciones de tono que podrían ser intencionales\n- Textos sin contexto suficiente para determinar el tono establecido\nSolo señala inconsistencias MUY CLARAS Y EVIDENTES.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"issueType":"cambio_registro|ruptura_pov|cambio_persona|intrusion_autor","establishedTone":"descripción del tono establecido","occurrence":{"text":"fragmento con la ruptura","location":"ubicación"},"explanation":"descripción"}]}\nDevuelve MÁXIMO 10 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"nombres_inconsistentes", groupId:"coherence", label:"Inconsistencia de nombres propios", description:"El mismo nombre escrito de formas distintas", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de inconsistencias en la grafía de nombres propios: el mismo nombre escrito de formas distintas (con o sin tilde, mayúsculas/minúsculas, grafías diferentes).\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"name":"nombre afectado","variants":["variante1","variante2"],"occurrences":[{"text":"fragmento","location":"ubicación"},{"text":"fragmento","location":"ubicación"}],"recommendedForm":"forma recomendada","explanation":"descripción"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"pov", groupId:"coherence", label:"Cambios de punto de vista (POV)", description:"Saltos entre perspectivas sin transición clara", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de cambios no controlados de punto de vista (POV): 1) En focalización fija, saltar a pensamientos de otro personaje sin transición. 2) En tercera persona limitada, el narrador accede a info que el personaje focal no puede saber. 3) Cabeza-hopping: cambiar de POV varias veces dentro de una escena.\nNO señales:\n- Textos breves (menos de 200 palabras) donde no hay suficiente contexto para determinar el POV establecido\n- Errores gramaticales como leísmos que no tienen que ver con el POV\n- Narrador omnisciente, que por definición puede acceder a todos los personajes\n- Casos donde el POV no está claramente establecido\nSolo señala cambios de POV MUY CLAROS Y EVIDENTES en textos suficientemente largos.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"focalCharacter":"personaje cuyo POV se usaba","intrudingCharacter":"personaje cuyo POV irrumpe","occurrence":{"text":"fragmento con el cambio","location":"ubicación"},"explanation":"descripción del problema"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},
];


})();
