// ============================================================================
// PLUMIA — corrections-config.js  v8.00
// COLOR_MAP, CONFIG, GROUPS, CORRECTIONS — namespace window.PLUMIA
// Expuesto como window.PLUMIA.* para compatibilidad con Office Add-in
// ============================================================================
(function() {
window.PLUMIA = {};
window.PLUMIA.CONFIG_VERSION = '8.00';
console.log('📦 corrections-config.js v8.00 cargado');
window.PLUMIA.COLOR_MAP = {
  1:{name:"Rojo",hex:"FF0000",type:"text"},
  2:{name:"Amarillo",hex:"FFD966",type:"highlight"},
  3:{name:"Verde claro",hex:"92D050",type:"highlight"},
  4:{name:"Naranja",hex:"FF9900",type:"highlight"},
  5:{name:"Turquesa",hex:"00B0F0",type:"highlight"},
  6:{name:"Rosa",hex:"FF69B4",type:"bracket"},
  7:{name:"Azul",hex:"0070C0",type:"text"},
  8:{name:"Lavanda",hex:"C9B8FF",type:"highlight"},
  9:{name:"Violeta",hex:"7030A0",type:"highlight"},
};

window.PLUMIA.CONFIG = {
  model:"claude-sonnet-4-20250514",
  maxTokens:8192,
  wordsPerToken:0.75,
  inputPricePerToken:0.000003,
  outputPricePerToken:0.000015,
  chunkSizeWords:3000,
  chunkOverlapWords:200,
  coherenceChunkSizeWords:80000,
  revisionSuffix:"REVISION",
  statsSuffix:"ESTADISTICAS",
};

window.PLUMIA.GROUPS = [
  {id:"pronouns",  label:"Pronombres y deixis"},
  {id:"lexicon",   label:"Léxico y vocabulario"},
  {id:"style",     label:"Estilo y fluidez"},
  {id:"grammar",   label:"Gramática"},
  {id:"orthotypo", label:"Ortotipografía"},
  {id:"coherence", label:"Coherencia narrativa", requiresFullDoc:true},
];

window.PLUMIA.CORRECTIONS = [
  {id:"leismo", groupId:"pronouns", label:"Leísmos, laísmos y loísmos", description:"Uso incorrecto de le, la, lo como complemento", colorId:1, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el siguiente texto en busca de leísmos, laísmos y loísmos: usos incorrectos de los pronombres le, la y lo.\nRecuerda:\n- "lo/la" son complemento directo (CD)\n- "le" es complemento indirecto (CI)\n- Leísmo: usar "le" donde corresponde "lo/la". Ej: "Le vi ayer" → "Lo vi ayer"\n- Laísmo: usar "la" donde corresponde "le". Ej: "La dije que viniera" → "Le dije que viniera"\n- Loísmo: usar "lo" donde corresponde "le". Ej: "Lo di el libro" → "Le di el libro"\nIgnora el leísmo de persona masculina singular si es el único caso.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"type":"leismo|laismo|loismo","originalText":"fragmento exacto","correction":"forma correcta","explanation":"explicación breve"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ningún error: {"findings":[]}`},

  {id:"ambiguedad_pronominal", groupId:"pronouns", label:"Ambigüedades pronominales", description:"Pronombres con referente poco claro", colorId:8, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de ambigüedades pronominales: casos en que pronombres como él, ella, lo, la, le, se, su no tienen un referente claro porque pueden aplicarse a más de un personaje o elemento en la misma frase o párrafo.\nPresta atención a escenas con varios personajes. Solo señala casos genuinamente ambiguos donde el lector no pueda saber a quién se refiere el pronombre.\nNO señales:\n- Pronombres cuyo referente es claro por contexto\n- Errores de leísmo, laísmo o loísmo (eso lo analiza otra categoría)\n- Frases donde el sujeto es obvio\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","pronoun":"pronombre ambiguo","possibleReferents":["ref1","ref2"],"explanation":"por qué es ambiguo","suggestion":"posible reformulación"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"repeticion_lexica", groupId:"lexicon", label:"Repeticiones léxicas cercanas", description:"Misma palabra repetida en corta distancia", colorId:2, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de repeticiones léxicas cercanas: la misma palabra (o su raíz) repetida en un radio de 3-5 líneas, sin intención estilística. No señales artículos, preposiciones, conjunciones, ni repeticiones deliberadas. Tampoco señales nombres propios (nombres de personajes, lugares o entidades): esas repeticiones se analizan por separado.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"word":"palabra base","occurrences":["fragmento 1","fragmento 2"],"explanation":"breve explicación","synonyms":["sin1","sin2","sin3"]}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"verbos_comedin", groupId:"lexicon", label:"Verbos comodín", description:"Abuso de hacer, poner, tener, dar, haber…", colorId:4, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de verbos comodín usados en exceso: hacer, poner, tener, dar, haber, decir, ver, ir, venir, coger, cuando podría usarse un verbo más preciso. Solo señala casos donde empobrezca claramente el estilo.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","verb":"verbo comodín","explanation":"por qué es mejorable","alternatives":["alt1","alt2","alt3"]}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"sustantivos_genericos", groupId:"lexicon", label:"Sustantivos genéricos", description:"Abuso de cosa, tema, aspecto, situación…", colorId:4, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de sustantivos genéricos: cosa, tema, aspecto, situación, elemento, cuestión, problema, algo, asunto, hecho, usados donde podría emplearse un término más concreto.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","genericWord":"palabra genérica","explanation":"por qué es mejorable","alternatives":["alt1","alt2","alt3"]}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"muletillas", groupId:"lexicon", label:"Muletillas narrativas", description:"Expresiones repetidas que no aportan valor", colorId:4, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de muletillas: palabras o expresiones que aparecen con demasiada frecuencia y no aportan información nueva. Ej: "en cierto modo", "de alguna manera", "de repente" repetido, "entonces", "básicamente", "realmente". Solo señala las que aparezcan al menos 2 veces o sean claramente innecesarias.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"expression":"muletilla","occurrences":["fragmento 1","fragmento 2"],"explanation":"por qué es muletilla","alternatives":["alt1","alt2","eliminar"]}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"pleonasmos", groupId:"lexicon", label:"Pleonasmos", description:"Palabras innecesarias que repiten información", colorId:4, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de pleonasmos: palabras innecesarias que repiten información ya contenida. Ej: "subir arriba", "bajar abajo", "entrar dentro", "salir fuera", "ver con mis propios ojos", "volver a reincidir".\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","explanation":"por qué es redundante","correction":"forma sin redundancia"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"adverbios_mente", groupId:"style", label:"Adverbios en -mente", description:"Evalúa cada adverbio en -mente: adecuado o mejorable para la narrativa", colorId:3, includesSynonyms:true, directFix:false,
   prompt:`Eres un editor literario experto en español. Analiza el texto buscando adverbios terminados en \"-mente\".\n\nPara CADA adverbio en \"-mente\" que encuentres:\n1. Cita la frase original exacta del texto.\n2. Indica el adverbio detectado.\n3. Evalúa su uso:\n   a) \"Adecuado\": aporta matiz, ritmo o precisión difícil de sustituir.\n   b) \"Mejorable\": redundante, débil o sustituible por algo más expresivo.\n4. Si es \"Mejorable\", propone 2 alternativas que:\n   - NO usen adverbios en \"-mente\" ni otros adverbios.\n   - Prioricen verbos más precisos, acciones concretas o recursos narrativos.\n   - Suenen naturales dentro de una novela.\n\nIMPORTANTE: No elimines adverbios que funcionen bien. Respeta los que aporten valor literario. Si el texto no contiene ninguna palabra terminada en \"-mente\", devuelve findings:[].\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{\"findings\":[{\"originalText\":\"frase exacta del texto\",\"adverb\":\"adverbio detectado\",\"evaluation\":\"Adecuado|Mejorable\",\"explanation\":\"por qué es adecuado o mejorable\",\"alternatives\":[\"alternativa 1\",\"alternativa 2\"]}]}\nSi no hay adverbios en -mente: {\"findings\":[]}`},

  {id:"voz_pasiva", groupId:"style", label:"Voz pasiva innecesaria", description:"Construcciones pasivas que podrían ser activas", colorId:5, includesSynonyms:true, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de construcciones en voz pasiva que resultarían más naturales en voz activa. Señala tanto la pasiva perifrástica ("fue abierto por") como la pasiva refleja innecesaria ("se abrió"). No señales cuando sea la opción más natural o sin agente claro.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento en voz pasiva","explanation":"por qué revisarlo","activeVersion":"reformulación en voz activa"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"frases_largas", groupId:"style", label:"Frases demasiado largas", description:"Oraciones de +40 palabras que dificultan la lectura", colorId:6, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de frases excesivamente largas (más de 40 palabras, o más cortas pero con estructura subordinada muy compleja) que dificulten la comprensión o rompan el ritmo.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"frase completa exacta","wordCount":45,"explanation":"por qué dificulta la lectura","suggestion":"cómo dividirla o simplificarla"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"nombres_propios", groupId:"style", label:"Exceso de nombres propios", description:"Repetición excesiva de nombres propios cercanos", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector de estilo experto en español. Analiza el texto en busca de nombres propios que se repiten con demasiada frecuencia en un fragmento corto, cuando podrían sustituirse por pronombres u otras referencias.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"name":"nombre propio","occurrences":["fragmento 1","fragmento 2"],"explanation":"por qué resulta excesivo","suggestion":"cómo aligerarlo"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"ritmo_narrativo", groupId:"style", label:"Ritmo narrativo", description:"Desequilibrios de ritmo entre escena y longitud de frases", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un editor literario experto en español. Analiza el texto en busca de desequilibrios de ritmo ESTRUCTURAL. Céntrate SOLO en:\n1) Acumulación de frases muy cortas y telegráficas en escenas descriptivas, de atmósfera o de calma, donde ese ritmo entrecortado rompe el tono contemplativo.\n2) Párrafos con densidad muy desigual sin intención estilística (un párrafo de 2-3 palabras junto a otro de 150+ palabras en el mismo tono emocional).\n\nNO señales NUNCA:\n- Frases largas: eso lo analiza la categoría «Frases demasiado largas» — no dupliques ese análisis aquí bajo ningún concepto\n- Textos de menos de 100 palabras\n- Frases cortas en escenas de acción o tensión (son estilísticamente correctas)\n- Frases cortas que sean deliberadamente impactantes o poéticas\n\nSolo señala casos donde el desequilibrio sea CLARO, EVIDENTE y PERJUDICIAL para la lectura.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","sceneType":"descripción|atmósfera|reflexión","issue":"descripción del desequilibrio","suggestion":"cómo mejorar el ritmo"}]}\nSi no encuentras ninguno o el texto es demasiado corto: {"findings":[]}`},

  {id:"numeros_letras", groupId:"style", label:"Números en letra", description:"Números del 0-99 que en texto literario deben escribirse con letras", colorId:3, includesSynonyms:false, directFix:false, prompt:''},

  {id:"gerundios", groupId:"grammar", label:"Gerundios incorrectos", description:"Gerundio de posterioridad y otros usos incorrectos", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector gramatical experto en español. Analiza el texto en busca de gerundios incorrectos: 1) Gerundio de posterioridad: acción posterior a la principal. Ej: "Salió de casa, encontrando a Juan". 2) Gerundio especificativo: "Una ley regulando el tráfico" → "que regula". 3) Gerundio como adjetivo: "Una caja conteniendo libros".\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","gerund":"gerundio problemático","errorType":"posterioridad|especificativo|adjetivo","explanation":"por qué es incorrecto","correction":"reformulación correcta"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"interrogativas_tilde", groupId:"grammar", label:"Tildes en interrogativos y exclamativos", description:"qué/que, cómo/como, cuándo/cuando, quién/quien, dónde/donde, cuánto/cuanto, cuál/cual", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de errores en el uso de tildes diacríticas en palabras interrogativas y exclamativas.\n\nREGLAS:\n- CON tilde (interrogativo/exclamativo): qué, cómo, cuándo, quién/quiénes, dónde, cuánto/cuánta/cuántos/cuántas, cuál/cuáles\n  → Preguntas directas: «¿Qué quieres?», «¿Cómo estás?», «¿Cuándo llegas?»\n  → Preguntas indirectas: «No sé qué pensar», «Me preguntó cómo lo hice», «Ignoro cuándo volverá»\n  → Exclamaciones: «¡Qué bonito!», «¡Cuánto tiempo!», «¡Cómo llueve!»\n- SIN tilde (conjunción/relativo/comparativo): que, como, cuando, quien/quienes, donde, cuanto/cuanta/cuantos/cuantas, cual/cuales\n  → Conjunción: «Dijo que vendría», «Cuando llegué estaba»\n  → Relativo: «El libro que leí», «Fue él quien lo hizo», «La ciudad donde nació»\n  → Comparativo/modal: «rápido como el viento», «Como llovía, me quedé», «Tanto como quieras»\n\nNO señales los casos inmediatamente tras ¿ o ¡ — ya los detecta el motor local. Céntrate en preguntas indirectas y tildes sobrantes en contexto relativo o conjuncional.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto con contexto suficiente","wordForm":"palabra detectada","correctForm":"forma correcta","errorType":"falta_tilde|tilde_sobrante","context":"interrogativo_directo|interrogativo_indirecto|exclamativo|relativo|conjuncion|comparativo","explanation":"por qué es incorrecto"}]}\nSi no encuentras ninguno: {"findings":[]}`},

  {id:"tu_tilde", groupId:"grammar", label:"Uso de «tú» con tilde diacrítica", description:"«tú» (pronombre personal sujeto) vs «tu» (posesivo, ante sustantivo)", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de errores en el uso de «tú» (con tilde diacrítica) y «tu» (sin tilde).\n\nREGLAS:\n- «tú» CON tilde: pronombre personal sujeto («Tú sabes», «Lo hiciste tú», «Eres tú», «¿Lo haces tú?»)\n- «tu» SIN tilde: posesivo determinante, siempre ante sustantivo («tu casa», «tu amor», «tu idea»)\n\nNO señales los casos de «que tu» seguido de puntuación — ya los detecta el motor local.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto con contexto suficiente","tuForm":"tu|tú","correctForm":"tú|tu","function":"pronombre_personal|posesivo","explanation":"por qué es incorrecto"}]}\nSi no encuentras ninguno: {"findings":[]}`},

  {id:"mi_tilde", groupId:"grammar", label:"Uso de «mí» con tilde diacrítica", description:"«mí» (pronombre personal, siempre tras preposición) vs «mi» (posesivo, ante sustantivo)", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de errores en el uso de «mí» (con tilde diacrítica) y «mi» (sin tilde).\n\nREGLAS:\n- «mí» CON tilde: pronombre personal, siempre tras preposición («a mí», «para mí», «de mí», «por mí», «sin mí», «sobre mí», «hacia mí»)\n- «mi» SIN tilde: posesivo, siempre ante sustantivo («mi casa», «mi amor», «mi idea»)\n\nNO señales los casos donde «mi» va seguido de puntuación (coma, punto, etc.) porque ya los detecta el motor local.\nSeñala SOLO los casos claramente incorrectos que requieran análisis de contexto:\n- «mi» tras preposición cuando actúa como pronombre y NO le sigue puntuación inmediata\n- «mí» ante un sustantivo donde claramente actúa como posesivo\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto del texto con contexto suficiente","miForm":"mi|mí","correctForm":"mí|mi","function":"pronombre_personal|posesivo","explanation":"por qué es incorrecto"}]}\nSi no encuentras ninguno: {"findings":[]}`},

  {id:"aun_tilde", groupId:"grammar", label:"Uso de «aún» con tilde diacrítica", description:"«aún» (= todavía) vs «aun» (= incluso/aunque) — detección local de patrones seguros", colorId:7, includesSynonyms:false, directFix:false, prompt:''},

  {id:"si_tilde", groupId:"grammar", label:"Uso de «sí» con tilde diacrítica", description:"«sí» (adverbio/pronombre reflexivo) vs «si» (conjunción condicional)", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de errores en el uso de «sí» (con tilde diacrítica) y «si» (sin tilde).\n\nREGLAS:\n- «sí» CON tilde: adverbio de afirmación ("Sí, quiero"), pronombre personal reflexivo ("volvió en sí", "para sí mismo", "en sí"), sustantivo de aprobación ("dio el sí")\n- «si» SIN tilde: conjunción condicional ("si llueve, me quedo"), interrogativa indirecta ("preguntó si vendría")\n\nSeñala SOLO los casos claramente incorrectos. NO señales casos ambiguos ni los que ya detecta el motor local (en sí, para sí, por sí mismo, fuera de sí).\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto del texto con contexto suficiente","siForm":"si|sí","correctForm":"sí|si","function":"adverbio_afirmacion|pronombre_reflexivo|sustantivo|condicional|interrogativa_indirecta","explanation":"por qué es incorrecto"}]}\nSi no encuentras ninguno: {"findings":[]}`},

  {id:"dequeismo", groupId:"grammar", label:"Dequeísmo y queísmo", description:"Uso incorrecto de 'de que' / omisión incorrecta", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector gramatical experto en español. Analiza el texto en busca de: 1) Dequeísmo: "de que" donde solo corresponde "que". Ej: "Pienso de que..." → "Pienso que...". 2) Queísmo: omitir "de" donde es necesaria. Ej: "Estoy seguro que..." → "Estoy seguro de que...".\nNO señales:\n- Errores de leísmo, laísmo o loísmo (eso lo analiza otra categoría)\n- Usos correctos de "de que" después de verbos que lo requieren\n- Frases que contienen errores de otro tipo pero no dequeísmo ni queísmo\nSolo señala si encuentras exactamente una construcción "de que" incorrecta o una omisión incorrecta de "de".\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","errorType":"dequeismo|queismo","explanation":"explicación breve","correction":"forma correcta"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"concordancia", groupId:"grammar", label:"Concordancia de género y número", description:"Errores de concordancia sujeto-verbo o sustantivo-adjetivo", colorId:7, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector gramatical experto en español. Analiza el texto en busca de errores de concordancia: 1) Sujeto-verbo: el verbo no concuerda en número con el sujeto. 2) Sustantivo-adjetivo: el adjetivo no concuerda en género o número. Ignora sujetos compuestos o colectivos con concordancia flexible.\nNO señales:\n- Errores de leísmo, laísmo o loísmo (eso lo analiza otra categoría). Por ejemplo, "La dije" es un laísmo, NO un error de concordancia.\n- Errores de otro tipo que no sean estrictamente de concordancia entre sujeto-verbo o sustantivo-adjetivo\n- Cualquier frase que simplemente te parezca incorrecta por otros motivos\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","errorType":"sujeto-verbo|sustantivo-adjetivo","explanation":"descripción del error","correction":"forma correcta"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"tiempos_verbales", groupId:"grammar", label:"Inconsistencia de tiempos verbales", description:"Mezcla no intencional de indefinido e imperfecto", colorId:5, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector literario experto en español. Analiza el texto en busca de posibles inconsistencias en tiempos verbales del pasado: mezclas no intencionales de pretérito indefinido (canté) e imperfecto (cantaba) dentro de una misma escena. Solo señala los que parezcan descuidos, no los cambios intencionales.\nNO señales:\n- Errores de leísmo, laísmo o loísmo (eso lo analiza otra categoría)\n- Frases con otros tipos de errores gramaticales que no sean de tiempo verbal\n- Cambios de tiempo verbal que son correctos y habituales (descripción en imperfecto + acción en indefinido)\nSolo marca si hay un cambio de tiempo verbal que rompa la coherencia temporal de la escena.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","verbsFound":["verbo indefinido","verbo imperfecto"],"explanation":"por qué podría ser descuido","suggestion":"cómo resolverlo"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"ortotipografia_pura", groupId:"orthotypo", label:"Ortotipografía pura", description:"Guiones, comillas, puntos suspensivos, mayúsculas, signos ¿¡, espaciado", colorId:null, includesSynonyms:false, directFix:true,
   prompt:`Eres un corrector ortotipográfico experto en español. Analiza el texto ÚNICAMENTE en busca de errores tipográficos y ortotipográficos. Corrige:\n1. Guiones de diálogo: guion corto (-) en lugar de raya (—)\n2. Comillas inglesas ("") en lugar de españolas («»)\n3. Tres puntos separados (...) en lugar del carácter tipográfico (…)\n4. Signos de apertura omitidos (¿ ¡)\n5. Espacio ANTES de coma, punto, punto y coma, dos puntos (NO después)\n6. Falta de mayúscula al inicio de párrafo o tras punto final\nNO corrijas NUNCA:\n- Errores gramaticales como leísmos, laísmos o loísmos. Por ejemplo, "La dije" es un laísmo gramatical, NO un error ortotipográfico. NO lo corrijas aquí.\n- Errores de concordancia, dequeísmo, gerundios ni ningún otro error gramatical\n- Estilo, vocabulario o estructura de las frases\nSolo señala y corrige errores puramente tipográficos.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"errorType":"guion|comillas|puntos_suspensivos|signo_apertura|espaciado|mayusculas","originalText":"fragmento exacto","correction":"fragmento corregido","isFirstOccurrence":true,"explanation":"solo si isFirstOccurrence: explicación breve"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"puntuacion_dialogo", groupId:"orthotypo", label:"Problemas de puntuación en diálogo", description:"Errores de puntuación en intervenciones y acotaciones", colorId:6, includesSynonyms:false, directFix:false,
   prompt:`Eres un corrector ortotipográfico experto en español. Analiza el texto en busca de errores EXCLUSIVAMENTE de puntuación en diálogos. IMPORTANTE: NO detectes ni reportes leísmos, laísmos, loísmos, ambigüedades pronominales ni ningún otro error gramatical — esos pertenecen a otras categorías. Céntrate SOLO en: 1) Falta de raya antes de la acotación: —Hola. dijo → —Hola —dijo. 2) Punto incorrecto antes de acotación. 3) Coma innecesaria antes de raya de cierre. 4) Mayúscula incorrecta en verbo de acotación. 5) Punto tras interrogación/exclamación: —¿Vienes?. → —¿Vienes? 6) Falta de punto tras acotación cuando el diálogo continúa. 7) Coma innecesaria después de interrogación. EXCLUYE cualquier frase que NO sea una intervención directa marcada con raya (—).\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"originalText":"fragmento exacto","errorType":"descripción breve del error","correction":"fragmento corregido","explanation":"explicación breve de la regla"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},

  {id:"coherencia_personajes", groupId:"coherence", label:"Coherencia de personajes", description:"Contradicciones en experiencias, habilidades o rasgos físicos", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto narrativo en busca de contradicciones en la caracterización de personajes: 1) Experiencias que se contradicen (afirma que es la primera vez pero ya lo hizo antes). 2) Habilidades que aparecen y desaparecen sin explicación. 3) Rasgos físicos que cambian sin justificación. 4) Conocimiento que un personaje no debería tener.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"characterName":"nombre del personaje","contradictionType":"experiencia|habilidad|rasgo_fisico|conocimiento","occurrence1":{"text":"fragmento exacto","location":"ubicación"},"occurrence2":{"text":"fragmento contradictorio","location":"ubicación"},"explanation":"descripción de la contradicción"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"coherencia_temporal", groupId:"coherence", label:"Coherencia temporal", description:"Inconsistencias en la línea de tiempo del relato", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de inconsistencias temporales: 1) Referencias temporales contradictorias. 2) Edades que no encajan con fechas mencionadas. 3) Estaciones del año contradictorias en el mismo período. 4) Eventos en orden imposible.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"inconsistencyType":"referencia_temporal|edad|estacion|orden_eventos","occurrence1":{"text":"fragmento exacto","location":"ubicación"},"occurrence2":{"text":"fragmento contradictorio","location":"ubicación"},"explanation":"descripción de la inconsistencia"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"coherencia_objetos", groupId:"coherence", label:"Coherencia de objetos y espacios", description:"Objetos que desaparecen o espacios que cambian sin explicación", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de inconsistencias en objetos o espacios: 1) Objeto importante que desaparece sin explicación. 2) Personaje usa un objeto que no podía tener. 3) Distribución de espacios que cambia entre escenas. 4) Personaje lleva algo que olvidó, perdió o entregó antes.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"itemOrSpace":"nombre del objeto/espacio","inconsistencyType":"objeto_desaparece|objeto_imposible|espacio_cambia","occurrence1":{"text":"fragmento exacto","location":"ubicación"},"occurrence2":{"text":"fragmento contradictorio","location":"ubicación"},"explanation":"descripción"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"coherencia_conocimiento", groupId:"coherence", label:"Coherencia de conocimiento", description:"Personajes que saben cosas que no deberían saber aún", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de inconsistencias en el conocimiento de personajes: 1) Un personaje sabe algo que aún no le han contado. 2) Un personaje actúa como si no supiera algo que vivió. 3) El narrador revela información que el personaje focal no podría conocer.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"characterName":"personaje","knowledgeIssue":"descripción","occurrence1":{"text":"fragmento","location":"ubicación"},"occurrence2":{"text":"fragmento contradictorio","location":"ubicación"},"explanation":"descripción"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"tono_voz", groupId:"coherence", label:"Tono y voz narrativa", description:"Cambios bruscos de registro o ruptura del punto de vista", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de inconsistencias CLARAS en tono y voz narrativa: 1) Cambios bruscos e injustificados de registro (de formal a muy coloquial). 2) El narrador rompe explícitamente el punto de vista establecido. 3) Cambios de persona narrativa no justificados. 4) Intrusiones del autor que rompen la ficción.\nNO señales:\n- Textos breves (menos de 200 palabras) donde es imposible evaluar el tono con fiabilidad\n- Errores gramaticales como leísmos que no tienen que ver con el tono\n- Variaciones de tono que podrían ser intencionales\n- Textos sin contexto suficiente para determinar el tono establecido\nSolo señala inconsistencias MUY CLARAS Y EVIDENTES.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"issueType":"cambio_registro|ruptura_pov|cambio_persona|intrusion_autor","establishedTone":"descripción del tono establecido","occurrence":{"text":"fragmento con la ruptura","location":"ubicación"},"explanation":"descripción"}]}\nDevuelve MÁXIMO 10 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"nombres_inconsistentes", groupId:"coherence", label:"Inconsistencia de nombres propios", description:"El mismo nombre escrito de formas distintas", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un corrector experto en español. Analiza el texto en busca de inconsistencias en la grafía de nombres propios: el mismo nombre escrito de formas distintas (con o sin tilde, mayúsculas/minúsculas, grafías diferentes).\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"name":"nombre afectado","variants":["variante1","variante2"],"occurrences":[{"text":"fragmento","location":"ubicación"},{"text":"fragmento","location":"ubicación"}],"recommendedForm":"forma recomendada","explanation":"descripción"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguna: {"findings":[]}`},

  {id:"pov", groupId:"coherence", label:"Cambios de punto de vista (POV)", description:"Saltos entre perspectivas sin transición clara", colorId:9, includesSynonyms:false, directFix:false, requiresFullDoc:true,
   prompt:`Eres un editor literario experto. Analiza el texto en busca de cambios no controlados de punto de vista (POV): 1) En focalización fija, saltar a pensamientos de otro personaje sin transición. 2) En tercera persona limitada, el narrador accede a info que el personaje focal no puede saber. 3) Cabeza-hopping: cambiar de POV varias veces dentro de una escena.\nNO señales:\n- Textos breves (menos de 200 palabras) donde no hay suficiente contexto para determinar el POV establecido\n- Errores gramaticales como leísmos que no tienen que ver con el POV\n- Narrador omnisciente, que por definición puede acceder a todos los personajes\n- Casos donde el POV no está claramente establecido\nSolo señala cambios de POV MUY CLAROS Y EVIDENTES en textos suficientemente largos.\n\nTexto a analizar:\n{TEXT}\n\nResponde ÚNICAMENTE con un JSON válido:\n{"findings":[{"focalCharacter":"personaje cuyo POV se usaba","intrudingCharacter":"personaje cuyo POV irrumpe","occurrence":{"text":"fragmento con el cambio","location":"ubicación"},"explanation":"descripción del problema"}]}\nDevuelve MÁXIMO 15 hallazgos. Si no encuentras ninguno: {"findings":[]}`},
];


})();
